# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ECG_Recorder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 327)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_recording = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_recording.setObjectName("pushButton_recording")
        self.horizontalLayout.addWidget(self.pushButton_recording)
        self.pushButton_port = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_port.setObjectName("pushButton_port")
        self.horizontalLayout.addWidget(self.pushButton_port)
        self.pushButton_filename = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_filename.setObjectName("pushButton_filename")
        self.horizontalLayout.addWidget(self.pushButton_filename)
        self.pushButton_baudrate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_baudrate.setObjectName("pushButton_baudrate")
        self.horizontalLayout.addWidget(self.pushButton_baudrate)
        self.label_HR = QtWidgets.QLabel(self.centralwidget)
        self.label_HR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_HR.setObjectName("label_HR")
        self.horizontalLayout.addWidget(self.label_HR)
        self.lcdNumber_HR = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_HR.setObjectName("lcdNumber_HR")
        self.horizontalLayout.addWidget(self.lcdNumber_HR)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        # self.plot = QtWidgets.QGraphicsView(self.centralwidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        # self.plot.setSizePolicy(sizePolicy)
        # self.plot.setObjectName("plot")
        # self.verticalLayout_2.addWidget(self.plot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_recording.setText(_translate("MainWindow", "Recording Start/Stop"))
        self.pushButton_port.setText(_translate("MainWindow", "Choose port"))
        self.pushButton_filename.setText(_translate("MainWindow", "Filename and path"))
        self.pushButton_baudrate.setText(_translate("MainWindow", "Set baudrate"))
        self.label_HR.setText(_translate("MainWindow", "Heart Rate"))
